from setuptools import setup, find_packages

setup(
    name="pymaf-x",
    version="0.0.1",
    packages=find_packages("src"),
    package_dir={"": "src"},
    package_data={
        "pymaf_x": ['src/pymaf_x/configs/*.yaml'],
    },
    include_package_data=True,
    # data_files=[()],
    author=[
        "Hongwen Zhang",
        "Yating Tian",
        "Yuxiang Zhang",
        "Mengcheng Li",
        "Liang An",
        "Zhenan Sun",
        "Yebin Liu",
    ],
    author_email=[""],
    url="https://github.com/ahrilab/Forked-PyMAF-X",
    description="[TPAMI 2023] PyMAF-X: Towards Well-aligned Full-body Model Regression from Monocular Images.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    install_requires=[],
    dependency_links=[],
    classifiers=[
        "Intended Audience :: Developers",
        "Intended Audience :: Researchers",
        "Natural Language :: English",
        "Operating System :: MacOS :: MacOS X",
        "Operating System :: POSIX",
        "Operating System :: POSIX :: BSD",
        "Operating System :: POSIX :: Linux",
        "Operating System :: Microsoft :: Windows",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
    ],
)
